package com.hcl.bss.domain;


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product")
public class Product implements java.io.Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "uidpk", nullable = false)
	private long uidpk;
	@Column(name = "product_id", nullable = false, length = 20)
	private String productId;
	@Column(name = "product_disp_name", nullable = false, length = 100)
	private String productDispName;
	@Column(name = "sku", nullable = false, length = 20)
	private String sku;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "product_exp_date", nullable = false, length = 3)
	private Date productExpDate;
	@Column(name = "updated_by", length = 50)
	private String updatedBy;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 3)
	private Date updatedDate;
	@Column(name = "created_by", length = 50)
	private String createdBy;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 3)
	private Date createdDate;

	public Product() {
	}

	public Product(long uidpk, String productDispName, String sku, Date productExpDate, Date updatedDate,
			Date createdDate) {
		this.uidpk = uidpk;
		this.productDispName = productDispName;
		this.sku = sku;
		this.productExpDate = productExpDate;
		this.updatedDate = updatedDate;
		this.createdDate = createdDate;
	}

	public Product(long uidpk, String productDispName, String sku, Date productExpDate, String updatedBy,
			Date updatedDate, String createdBy, Date createdDate) {
		this.uidpk = uidpk;
		this.productDispName = productDispName;
		this.sku = sku;
		this.productExpDate = productExpDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
	}

	

	
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	
	public long getUidpk() {
		return this.uidpk;
	}

	public void setUidpk(long uidpk) {
		this.uidpk = uidpk;
	}

	
	public String getProductDispName() {
		return this.productDispName;
	}

	public void setProductDispName(String productDispName) {
		this.productDispName = productDispName;
	}

	
	public String getSku() {
		return this.sku;
	}

	public void setSku(String sku) {
		this.sku = sku;
	}

	
	public Date getProductExpDate() {
		return this.productExpDate;
	}

	public void setProductExpDate(Date productExpDate) {
		this.productExpDate = productExpDate;
	}

	
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Override
	public String toString() {
		return "Product [uidpk=" + uidpk + ", productId=" + productId + ", productDispName=" + productDispName
				+ ", sku=" + sku + ", productExpDate=" + productExpDate + ", updatedBy=" + updatedBy + ", updatedDate="
				+ updatedDate + ", createdBy=" + createdBy + ", createdDate=" + createdDate + "]";
	}

}
